import AuthProvider from "@/components/AuthProvider/AuthProvider";
import "./globals.scss";
import { Montserrat, Lato, Poppins, Open_Sans } from "next/font/google";
// import ContextProvider from "@/components/contextProvider/ContextProvider";

const montserrat = Montserrat({
    subsets: ["latin"],
    display: "swap",
    variable: "--montserrat-font",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const lato = Lato({
    weight: ["100", "300", "400", "700", "900"],
    style: ["normal", "italic"],
    subsets: ["latin"],
    display: "swap",
    variable: "--lato-font",
});
const poppins = Poppins({
    subsets: ["latin"],
    style: ["italic", "normal"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    display: "swap",
    variable: "---poppins-font",
});

const opensSans = Open_Sans({
    subsets: ["latin"],
    style: ["italic", "normal"],
    weight: ["300", "400", "500", "600", "700", "800"],
    display: "swap",
    variable: "--opensans-font",
});
export const metadata = {
    title: "Board",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${montserrat.className} ${lato.className} ${poppins.className} ${opensSans.className}`}
            >
                <AuthProvider>
                    {/* <ContextProvider> */}
                    {children}
                    {/* </ContextProvider> */}
                </AuthProvider>
            </body>
        </html>
    );
}
